name: brux
favicon: null
layout_spectrum: 0.95052
typography_spectrum: 0.26919
title: BRUX - Büro für Webdesign
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cacacc'
    - '#a5afb9'
    - '#6c757e'
    - '#7a8b9b'
    - '#616669'
  brandStrength: 0.5
  lightness: 0.9234236644115299
  saturation: 0.9292450421489775
  rhythmicContrast: 0.5
purpose: []
