name: brux
favicon: null
layout_spectrum: 0.90238
typography_spectrum: 0.26919
title: BRUX - Büro für Webdesign
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5aaa1'
    - '#cf9b96'
    - '#b78c8a'
    - '#a27a79'
    - '#987170'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
