name: brux
favicon: null
layout_spectrum: 0.82562
typography_spectrum: 0.80948
title: 'BRUX '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5aaa1'
    - '#cf9b96'
    - '#b78c8a'
    - '#a27a79'
    - '#987170'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
